FROM node:20-slim

# Installa Chromium e le dipendenze necessarie per eseguirlo in modalità headless
RUN apt-get update && apt-get install -y \
    chromium \
    fonts-liberation \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    xdg-utils \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Installa puppeteer core
RUN npm init -y && \
    npm install puppeteer-core

COPY bot.js .

CMD ["node", "bot.js"]